### ISSUE TITLE
Vivecraft Incompatible with Intel HD Graphics

### ISSUE THREAD

**Issue by jakers1403** [jrbudda/Vivecraft_112#7] opened 2017-08-04 01:41 UTC
I'm sure you may know of this already, but Intel HD graphics wont work with Vivecraft.
The issue:
Vivecraft shows in the Minecraft window but not in HMD.
I read the troubleshooting but did not find it helpful as I do not have a secondary graphics card.
Specs:
Intel Core I3-4130
Intel HD graphics 4400
8GB Ram (7.41 usable)
Windows 8.1

I have tried everything and finally decided to ask if this could be fixed.
Thank you for reading this!

**Comment by jrbudda** [comment] 2017-08-04 02:05
Do any other SteamVR games work? Maybe you have to use extended mode?
I doubt you will get acceptable VR performance with your hardware even if you do get it running.

**Comment by jakers1403** [comment] 2017-08-04 20:03
Thanks for responding so quickly! Almost all SteamVR games work except those using unreal engine. The only reason I can actually play most VR games is becuase I use a DIY vr rig using riftcat with a phone that does 60 FPS. It has head positional and rotational tracking and motion controllers with psmoveservice. I have tried extended mode and it doesnt seem to help either. If there is no way to fix this I will most likely get a new graphics card. Almost all of the VR games I have run at acceptable framerates in the low settings.

**Comment by Techjar** [comment] 2017-08-04 20:10
I mean, in theory it should work if other SteamVR games are working. Can you upload the latest.log so I can take a look?

**Comment by jrbudda** [comment] 2017-08-04 20:11
if unreal engine doesnt work either then I highly doubt it's something we can fix on our end.

**Comment by jrbudda** [comment] 2017-08-04 20:28
tho I think there's a function in newer OpenVR versions that do ... something.. with available graphics adapters. Not particularly keen on updating OpenVR at this point in time.

**Comment by jakers1403** [comment] 2017-08-04 20:45
I couldnt get it to load a world right now although it usually does this with no problem. 
Here is the latest.log:
[latest.log.txt](https://github.com/jrbudda/Vivecraft_112/files/1201596/latest.log.txt)

**Comment by Techjar** [comment] 2017-08-04 20:46
```
[13:35:58] [main/ERROR]: Texture submission error: Left/Right TextureUsesUnsupportedFormat:/TextureUsesUnsupportedFormat:
```

This looks like the cause of the problem.

**Comment by Techjar** [comment] 2017-08-04 20:53
It looks if you have shaders enabled, which will probably end badly on Intel GPU. Make sure the shaders are set to "OFF" and not "(internal)".

**Comment by jakers1403** [comment] 2017-08-04 20:55
Yeah I saw that when i looked through the log. It may be my graphics card. SteamVR detects the game but it says (unresponsive) javaw.exe .

**Comment by Techjar** [comment] 2017-08-04 20:55
Yeah that's what SteamVR does when it's not getting any frames from the game.

**Comment by jakers1403** [comment] 2017-08-04 20:55
Even with the shaders problem aside. The menu wont even show on the HMD.

**Comment by MCWithMC** [comment] 2017-08-04 20:57
I know you said you tried everything, but have you tried software rendering in Riftcat to test?

**Comment by Techjar** [comment] 2017-08-04 20:58
I don't see how that would help, as this is texture submission issue between the game and OpenVR.

**Comment by jakers1403** [comment] 2017-08-04 21:01
I tried MCWithMC's sugestion and that didnt help. So is the problem with Intel HD graphics?

**Comment by Techjar** [comment] 2017-08-04 21:04
Yeah I can't see it being anything else, we are using the correct texture format. The Intel GPU just doesn't seem to be doing the right thing with the textures.

**Comment by Techjar** [comment] 2017-08-04 21:06
Unfortunately all I can tell you to do is get a dedicated GPU, as I don't think we can fix this. Find one that's cheap and decent on ebay or something, don't buy a new low-end GPU (like non-GTX NVIDIA ones), those are a waste of money.

**Comment by jakers1403** [comment] 2017-08-04 21:09
Thank you! Just wanted to see if this could be fixed.

**Comment by jakers1403** [comment] 2017-08-05 00:07
Should I close this now or is there more you need?

**Comment by Techjar** [comment] 2017-08-05 00:08
Nope, we can't solve this as far as I can tell, so feel free to close it.

**Closed** 2017-08-05 00:09 UTC
